#!/usr/bin/env sh

# Check if SIP is disabled
SIP_STATUS=$(csrutil status)

# If disabled, load Yabai scripting additions
if echo "$SIP_STATUS" | grep -qE "System Integrity Protection status: (disabled|unknown)"; then
    echo "SIP is disabled. Loading Yabai scripting additions."
    sudo yabai --load-sa
    yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
else
    echo "SIP is enabled. Skipping Yabai scripting additions."
fi

# Add signal for window focus event
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# General Settings
PADDING=2

yabai -m config external_bar all:39:0 \
    layout bsp \
    mouse_follows_focus on \
    focus_follows_mouse autoraise \
    split_ratio 0.5 \
    \
    window_zoom_persist off \
    window_topmost off \
    window_shadow float \
    window_opacity on \
    window_opacity_duration 0.2 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.95 \
    window_animation_duration 0.3 \
    \
    window_gap $PADDING \
    top_padding $PADDING \
    bottom_padding $PADDING \
    left_padding $PADDING \
    right_padding $PADDING \
    \
    auto_balance off \
    auto_padding on \
    mouse_modifier fn \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap

# Exclude problematic apps from being managed
EXLUDED_APPS=".*(Calendar|Finder|FaceTime|MetaMask|Boom 3D|Digital Colour Meter|Notes|zoom.us|Photo Booth|Calculator|App Store).*"
EXCLUDE_RULE=".*($EXLUDED_APPS|Huddle|Monitor|System|Settings|Preferences|Information|Progress|General|Utility|Auth|Sign|Password|Website|Extension|AutoFill|Search|Security|Privacy|Advance|Copy|Connect|Move|Info|Pref).*"
EXCLUDE_NON_LABEL=".*($EXCLUDE_RULE|MongoDB|Surfshark|NordVPN|CyberGhost).*"

# Manage Rules
yabai -m rule --add app="$EXCLUDE_NON_LABEL" manage=off
yabai -m rule --add title="$EXCLUDE_NON_LABEL" manage=off
yabai -m rule --add label="$EXCLUDE_RULE" manage=off

# Floating Rules
yabai -m rule --add app="$EXCLUDE_NON_LABEL" float=on
yabai -m rule --add title="$EXCLUDE_NON_LABEL" float=on
yabai -m rule --add label="$EXCLUDE_RULE" float=on
